import sys
# Assuming src.logger sets up basicConfig as shown in previous responses.
# The 'from src.logger import logging' line is likely redundant if logging
# is configured via basicConfig in the other file.
# We will use the standard logging module here.
import logging 

# --- Custom Exception Logic ---

def error_message_detail(error, error_detail: sys):
    """
    Formats the error message to include file name, line number, and error message.
    """
    _, _, exc_tb = error_detail.exc_info()
    file_name = exc_tb.tb_frame.f_code.co_filename
    error_message = "Error occurred in python script name [{0}] line number [{1}] error message [{2}]".format(
        file_name, exc_tb.tb_lineno, str(error)
    )
    return error_message

class CustomException(Exception):
    """
    Custom Exception class that captures detailed error context.
    """
    def __init__(self, error_message, error_detail: sys):
        # Calls the constructor of the parent Exception class
        super().__init__(error_message) 
        # Stores the detailed error message generated by the helper function
        self.error_message = error_message_detail(error_message, error_detail=error_detail)

    def __str__(self):
        # Overrides the string representation of the exception
        return self.error_message

# --- Main Execution Block ---

if __name__ == "__main__":
    # Configure logging for demonstration if not already done in src.logger
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

   